/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddSuperAdminRequest } from '../model/models';
import { CreateOrganizationRequest } from '../model/models';
import { OrganizationPage } from '../model/models';
import { OrganizationResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UserResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Neuen Super-Admin hinzufügen (Super-Admin)
     * Erteilt einem bestehenden Nutzer die SUPER_ADMIN Rolle.
     * @endpoint post /admin/super-admins
     * @param addSuperAdminRequest 
     */
    addSuperAdmin(addSuperAdminRequest: AddSuperAdminRequest, extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Neue Organisation anlegen (Super-Admin)
     * Legt eine neue Organisation an und sendet eine Einladungs-E-Mail an die angegebene Admin-E-Mail-Adresse. 
     * @endpoint post /admin/organizations
     * @param createOrganizationRequest 
     */
    createOrganization(createOrganizationRequest: CreateOrganizationRequest, extraHttpRequestParams?: any): Observable<OrganizationResponse>;

    /**
     * Organisation löschen (Super-Admin, Hard Delete)
     * 
     * @endpoint delete /admin/organizations/{orgId}
     * @param orgId 
     */
    deleteOrganization(orgId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Alle Organisationen auflisten (Super-Admin)
     * 
     * @endpoint get /admin/organizations
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     */
    listOrganizations(page?: number, size?: number, extraHttpRequestParams?: any): Observable<OrganizationPage>;

}
