/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddSuperAdminRequest } from '../model/models';
import { CreateOrganizationRequest } from '../model/models';
import { OrganizationPage } from '../model/models';
import { OrganizationResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { SuperAdminInvitationResponse } from '../model/models';
import { SuperAdminPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Neuen Super-Admin einladen (Super-Admin)
     * Sendet eine Einladungs-E-Mail an die angegebene Adresse. Der Eingeladene erhält die Rolle SUPER_ADMIN ohne Organisationszugehörigkeit. Kein bestehender Account erforderlich. 
     * @endpoint post /admin/super-admins
     * @param addSuperAdminRequest 
     */
    addSuperAdmin(addSuperAdminRequest: AddSuperAdminRequest, extraHttpRequestParams?: any): Observable<SuperAdminInvitationResponse>;

    /**
     * Neue Organisation anlegen (Super-Admin)
     * Legt eine neue Organisation an und sendet eine Einladungs-E-Mail an die angegebene Admin-E-Mail-Adresse. 
     * @endpoint post /admin/organizations
     * @param createOrganizationRequest 
     */
    createOrganization(createOrganizationRequest: CreateOrganizationRequest, extraHttpRequestParams?: any): Observable<OrganizationResponse>;

    /**
     * Organisation löschen (Super-Admin, Hard Delete)
     * Löscht eine Organisation vollständig und unwiderruflich.  **Kaskadierendes Löschen** – folgende Daten werden automatisch mitgelöscht: - Alle Mitglieder der Organisation (User-Accounts) - Alle Tasks aller Mitglieder - Alle Breaks aller Mitglieder - Alle Schedule-Einträge aller Mitglieder - Alle offenen Einladungen der Organisation - Alle Refresh-Tokens der Mitglieder  Nur für Nutzer mit Rolle &#x60;SUPER_ADMIN&#x60;. 
     * @endpoint delete /admin/organizations/{orgId}
     * @param orgId 
     */
    deleteOrganization(orgId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Super-Admin entfernen (Super-Admin, Hard Delete)
     * Löscht einen anderen Super-Admin vollständig aus dem System inklusive aller zugehörigen Daten.  **Einschränkung:** Ein Super-Admin kann sich nicht selbst löschen. Wenn &#x60;superAdminId&#x60; der eigenen &#x60;sub&#x60;-Claim aus dem JWT entspricht, wird der Request mit &#x60;403 Forbidden&#x60; abgelehnt.  Nur für Nutzer mit Rolle &#x60;SUPER_ADMIN&#x60;. 
     * @endpoint delete /admin/super-admins/{superAdminId}
     * @param superAdminId UUID des zu löschenden Super-Admins (darf nicht die eigene UUID sein)
     */
    deleteSuperAdmin(superAdminId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Alle Organisationen auflisten (Super-Admin)
     * 
     * @endpoint get /admin/organizations
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     */
    listOrganizations(page?: number, size?: number, extraHttpRequestParams?: any): Observable<OrganizationPage>;

    /**
     * Alle Super-Admins auflisten (Super-Admin)
     * 
     * @endpoint get /admin/super-admins
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     */
    listSuperAdmins(page?: number, size?: number, extraHttpRequestParams?: any): Observable<SuperAdminPage>;

}
