export * from './admin.service';
import { AdminService } from './admin.service';
export * from './admin.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './breaks.service';
import { BreaksService } from './breaks.service';
export * from './breaks.serviceInterface';
export * from './invitations.service';
import { InvitationsService } from './invitations.service';
export * from './invitations.serviceInterface';
export * from './members.service';
import { MembersService } from './members.service';
export * from './members.serviceInterface';
export * from './organizations.service';
import { OrganizationsService } from './organizations.service';
export * from './organizations.serviceInterface';
export * from './schedule.service';
import { ScheduleService } from './schedule.service';
export * from './schedule.serviceInterface';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './tasks.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export * from './workingHours.service';
import { WorkingHoursService } from './workingHours.service';
export * from './workingHours.serviceInterface';
export const APIS = [AdminService, AuthService, BreaksService, InvitationsService, MembersService, OrganizationsService, ScheduleService, TasksService, UsersService, WorkingHoursService];
