/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceptInvitationRequest } from '../model/models';
import { ChangePasswordRequest } from '../model/models';
import { InvitationTokenInfoResponse } from '../model/models';
import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { RefreshResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Einladung annehmen und Account erstellen
     * Öffentlicher Endpunkt (kein JWT erforderlich). Der Nutzer setzt sein Passwort und wird direkt eingeloggt. Der Einladungstoken ist 48 Stunden gültig. 
     * @endpoint post /auth/invitations/{token}/accept
     * @param token UUID-Token aus dem Einladungslink
     * @param acceptInvitationRequest 
     */
    acceptInvitation(token: string, acceptInvitationRequest: AcceptInvitationRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Passwort ändern
     * 
     * @endpoint post /auth/password/change
     * @param changePasswordRequest 
     */
    changePassword(changePasswordRequest: ChangePasswordRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Informationen zu einem Einladungstoken abrufen
     * Öffentlicher Endpunkt (kein JWT erforderlich). Gibt die E-Mail-Adresse zurück, die mit dem Token verknüpft ist. Wird genutzt, um das Registrierungsformular vorauszufüllen. 
     * @endpoint get /auth/invitations/{token}
     * @param token UUID-Token aus dem Einladungslink
     */
    getInvitationInfo(token: string, extraHttpRequestParams?: any): Observable<InvitationTokenInfoResponse>;

    /**
     * Login mit E-Mail und Passwort
     * Gibt den Access Token im Response Body zurück. Setzt den Refresh Token als HttpOnly Cookie (nicht im Body). Der Cookie ist auf &#x60;Path&#x3D;/api/v1/auth&#x60; beschränkt und wird vom Browser ausschließlich an &#x60;/auth/refresh&#x60; und &#x60;/auth/logout&#x60; mitgesendet. 
     * @endpoint post /auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Logout – Refresh Token invalidieren
     * Liest den Refresh Token aus dem HttpOnly Cookie und invalidiert ihn serverseitig. Löscht den Cookie durch Setzen von Max-Age&#x3D;0. Kein Request Body erforderlich – der Cookie wird vom Browser automatisch mitgesendet. 
     * @endpoint post /auth/logout
     * @param refreshToken HttpOnly Refresh Token Cookie (wird vom Browser automatisch mitgesendet)
     */
    logout(refreshToken: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Access Token erneuern (Token Rotation)
     * Liest den Refresh Token aus dem HttpOnly Cookie &#x60;refresh_token&#x60;. Gibt einen neuen Access Token im Body zurück und setzt einen neuen Refresh Token Cookie. Der alte Refresh Token Cookie wird serverseitig invalidiert (Token Rotation). Kein Request Body erforderlich – der Cookie wird vom Browser automatisch mitgesendet. 
     * @endpoint post /auth/refresh
     * @param refreshToken HttpOnly Refresh Token Cookie (wird vom Browser automatisch mitgesendet)
     */
    refreshToken(refreshToken: string, extraHttpRequestParams?: any): Observable<RefreshResponse>;

}
