/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceptInvitationRequest } from '../model/models';
import { ChangePasswordRequest } from '../model/models';
import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { RefreshRequest } from '../model/models';
import { RefreshResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Einladung annehmen und Account erstellen
     * Öffentlicher Endpunkt (kein JWT erforderlich). Der Nutzer setzt sein Passwort und wird direkt eingeloggt. Der Einladungstoken ist 48 Stunden gültig. 
     * @endpoint post /auth/invitations/{token}/accept
     * @param token UUID-Token aus dem Einladungslink
     * @param acceptInvitationRequest 
     */
    acceptInvitation(token: string, acceptInvitationRequest: AcceptInvitationRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Passwort ändern
     * 
     * @endpoint post /auth/password/change
     * @param changePasswordRequest 
     */
    changePassword(changePasswordRequest: ChangePasswordRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Login mit E-Mail und Passwort
     * Gibt Access Token und Refresh Token zurück.
     * @endpoint post /auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Logout – Refresh Token invalidieren
     * Invalidiert den übergebenen Refresh Token serverseitig.
     * @endpoint post /auth/logout
     * @param refreshRequest 
     */
    logout(refreshRequest: RefreshRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Access Token erneuern (Token Rotation)
     * Gibt einen neuen Access Token und einen neuen Refresh Token zurück. Der alte Refresh Token wird invalidiert (Token Rotation). 
     * @endpoint post /auth/refresh
     * @param refreshRequest 
     */
    refreshToken(refreshRequest: RefreshRequest, extraHttpRequestParams?: any): Observable<RefreshResponse>;

}
