/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BreakResponse } from '../model/models';
import { CreateBreakRequest } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BreaksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Neue Pause erstellen
     * 
     * @endpoint post /breaks
     * @param createBreakRequest 
     */
    createBreak(createBreakRequest: CreateBreakRequest, extraHttpRequestParams?: any): Observable<BreakResponse>;

    /**
     * Pause löschen (Hard Delete)
     * 
     * @endpoint delete /breaks/{breakId}
     * @param breakId UUID der Pause
     */
    deleteBreak(breakId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Eigene Pausen abrufen
     * Erstellt eine neue Pause. Das Verhalten hängt vom &#x60;breakType&#x60; ab: - &#x60;ONE_TIME&#x60; – einmalig an &#x60;date&#x60;, keine Wiederholung. - &#x60;RECURRING&#x60; – wiederkehrend ohne Enddatum. - &#x60;BOUNDED_RECURRING&#x60; – wiederkehrend nur zwischen &#x60;validFrom&#x60; und &#x60;validUntil&#x60;.  Der Planungsalgorithmus berücksichtigt die Pause ab dem nächsten &#x60;POST /schedule/generate&#x60; automatisch als Budgetabzug. 
     * @endpoint get /breaks
     */
    listBreaks(extraHttpRequestParams?: any): Observable<Array<BreakResponse>>;

    /**
     * Pause aktualisieren
     * Ersetzt eine Pause vollständig (PUT-Semantik). &#x60;breakType&#x60; kann geändert werden – dabei müssen alle Felder des neuen Typs gesetzt und die alten auf null gesetzt werden. 
     * @endpoint put /breaks/{breakId}
     * @param breakId UUID der Pause
     * @param createBreakRequest 
     */
    updateBreak(breakId: string, createBreakRequest: CreateBreakRequest, extraHttpRequestParams?: any): Observable<BreakResponse>;

}
