/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BreakResponse } from '../model/models';
import { CreateBreakRequest } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BreaksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Neue Pause erstellen
     * 
     * @endpoint post /breaks
     * @param createBreakRequest 
     */
    createBreak(createBreakRequest: CreateBreakRequest, extraHttpRequestParams?: any): Observable<BreakResponse>;

    /**
     * Pause löschen (Hard Delete)
     * 
     * @endpoint delete /breaks/{breakId}
     * @param breakId UUID der Pause
     */
    deleteBreak(breakId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Eigene Pausen abrufen
     * Gibt alle konfigurierten Pausen des eingeloggten Nutzers zurück.
     * @endpoint get /breaks
     */
    listBreaks(extraHttpRequestParams?: any): Observable<Array<BreakResponse>>;

    /**
     * Pause aktualisieren
     * 
     * @endpoint put /breaks/{breakId}
     * @param breakId UUID der Pause
     * @param createBreakRequest 
     */
    updateBreak(breakId: string, createBreakRequest: CreateBreakRequest, extraHttpRequestParams?: any): Observable<BreakResponse>;

}
