/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceptInvitationRequest } from '../model/models';
import { CreateInvitationRequest } from '../model/models';
import { InvitationPage } from '../model/models';
import { InvitationResponse } from '../model/models';
import { LoginResponse } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InvitationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Einladung annehmen und Account erstellen
     * Öffentlicher Endpunkt (kein JWT erforderlich). Der Nutzer setzt sein Passwort und wird direkt eingeloggt. Der Einladungstoken ist 48 Stunden gültig. 
     * @endpoint post /auth/invitations/{token}/accept
     * @param token UUID-Token aus dem Einladungslink
     * @param acceptInvitationRequest 
     */
    acceptInvitation(token: string, acceptInvitationRequest: AcceptInvitationRequest, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Einladung per E-Mail versenden
     * Sendet eine Einladungs-E-Mail mit einem Einmal-Token-Link an die angegebene Adresse. Der Token ist 48 Stunden gültig. Nur für Nutzer mit Rolle ADMIN oder höher. 
     * @endpoint post /organizations/me/invitations
     * @param createInvitationRequest 
     */
    createInvitation(createInvitationRequest: CreateInvitationRequest, extraHttpRequestParams?: any): Observable<InvitationResponse>;

    /**
     * Offene Einladungen auflisten
     * Nur für Nutzer mit Rolle ADMIN oder höher.
     * @endpoint get /organizations/me/invitations
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     */
    listInvitations(page?: number, size?: number, extraHttpRequestParams?: any): Observable<InvitationPage>;

    /**
     * Einladung widerrufen
     * Invalidiert den Einladungslink. Nur für Nutzer mit Rolle ADMIN oder höher.
     * @endpoint delete /organizations/me/invitations/{invitationId}
     * @param invitationId 
     */
    revokeInvitation(invitationId: string, extraHttpRequestParams?: any): Observable<{}>;

}
