/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MemberPage } from '../model/models';
import { MemberResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UpdateMemberRoleRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MembersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Alle Mitglieder der Organisation auflisten
     * Nur für Nutzer mit Rolle ADMIN oder höher.
     * @endpoint get /organizations/me/members
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     */
    listMembers(page?: number, size?: number, extraHttpRequestParams?: any): Observable<MemberPage>;

    /**
     * Mitglied aus der Organisation entfernen (Hard Delete)
     * Entfernt ein Mitglied vollständig aus dem System. Durch Datenbank-Kaskaden werden dabei automatisch gelöscht: - Alle Tasks des Mitglieds - Alle Breaks des Mitglieds - Alle Schedule-Einträge des Mitglieds - Alle Refresh-Tokens des Mitglieds  Nur für Nutzer mit Rolle &#x60;ADMIN&#x60; oder höher.  **Einschränkung:** Der letzte &#x60;ADMIN&#x60; einer Organisation kann nicht entfernt werden (&#x60;409 Conflict&#x60;). Es muss mindestens ein Admin in der Organisation verbleiben. 
     * @endpoint delete /organizations/me/members/{userId}
     * @param userId UUID des Nutzers
     */
    removeMember(userId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Rolle eines Mitglieds ändern
     * Nur für Nutzer mit Rolle ADMIN oder höher.
     * @endpoint patch /organizations/me/members/{userId}/role
     * @param userId UUID des Nutzers
     * @param updateMemberRoleRequest 
     */
    updateMemberRole(userId: string, updateMemberRoleRequest: UpdateMemberRoleRequest, extraHttpRequestParams?: any): Observable<MemberResponse>;

}
