/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OrganizationResponse } from '../model/models';
import { ProblemDetail } from '../model/models';
import { UpdateOrganizationSettingsRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrganizationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Eigene Organisation abrufen
     * 
     * @endpoint get /organizations/me
     */
    getMyOrganization(extraHttpRequestParams?: any): Observable<OrganizationResponse>;

    /**
     * Organisationseinstellungen aktualisieren
     * Nur für Nutzer mit Rolle ADMIN oder höher.
     * @endpoint put /organizations/me/settings
     * @param updateOrganizationSettingsRequest 
     */
    updateOrganizationSettings(updateOrganizationSettingsRequest: UpdateOrganizationSettingsRequest, extraHttpRequestParams?: any): Observable<OrganizationResponse>;

}
