/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';
import { RecurringExceptionRequest } from '../model/models';
import { RecurringExceptionResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RecurringScheduleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Ausnahme für ein RecurringTemplate-Vorkommen anlegen
     * Legt eine &#x60;RecurringException&#x60; für ein einzelnes Vorkommen an (Upsert-Semantik). Mögliche Typen: - &#x60;COMPLETED&#x60; – Vorkommen abgehakt. Bleibt als Budgetabzug beim Algorithmus. - &#x60;PINNED&#x60; – Vorkommen fixiert. Erscheint mit &#x60;isPinned: true&#x60;. - &#x60;SKIPPED&#x60; – Vorkommen übersprungen. Kein Budgetabzug beim Algorithmus   (mehr Budget für einmalige Tasks an diesem Tag). - &#x60;RESCHEDULED&#x60; – Vorkommen verschoben auf &#x60;newDate&#x60;/&#x60;newStartTime&#x60;.   Budgetabzug bleibt am ursprünglichen Tag erhalten.  Pro &#x60;(templateId, occurrenceDate)&#x60; existiert maximal eine Exception. Ein erneuter POST überschreibt die bestehende Exception. 
     * @endpoint post /schedule/recurring/{templateId}/exceptions
     * @param templateId UUID des RecurringTemplate
     * @param recurringExceptionRequest 
     */
    createRecurringException(templateId: string, recurringExceptionRequest: RecurringExceptionRequest, extraHttpRequestParams?: any): Observable<RecurringExceptionResponse>;

    /**
     * Ausnahme eines Vorkommens entfernen (Undo)
     * Löscht die &#x60;RecurringException&#x60; – das Vorkommen kehrt zum Normalzustand zurück. - &#x60;COMPLETED&#x60; → erscheint wieder als offen - &#x60;PINNED&#x60; → nicht mehr fixiert - &#x60;SKIPPED&#x60; → erscheint wieder im Plan - &#x60;RESCHEDULED&#x60; → erscheint wieder am ursprünglichen Datum/Zeit 
     * @endpoint delete /schedule/recurring/{templateId}/exceptions/{occurrenceDate}
     * @param templateId UUID des RecurringTemplate
     * @param occurrenceDate Datum des Vorkommens (ISO 8601)
     */
    deleteRecurringException(templateId: string, occurrenceDate: string, extraHttpRequestParams?: any): Observable<{}>;

}
