/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRecurringTemplateRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { RecurringTemplatePage } from '../model/models';
import { RecurringTemplateResponse } from '../model/models';
import { UpdateRecurringTemplateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RecurringTemplatesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Neues RecurringTemplate erstellen
     * Erstellt eine neue wiederkehrende Aufgaben-Vorlage. Ab dem nächsten &#x60;POST /schedule/generate&#x60; wird die Dauer des Templates täglich als Budgetabzug berücksichtigt. In &#x60;GET /schedule&#x60; erscheinen die Vorkommen automatisch als virtuelle Einträge (&#x60;source: RECURRING&#x60;). 
     * @endpoint post /recurring-templates
     * @param createRecurringTemplateRequest 
     */
    createRecurringTemplate(createRecurringTemplateRequest: CreateRecurringTemplateRequest, extraHttpRequestParams?: any): Observable<RecurringTemplateResponse>;

    /**
     * RecurringTemplate löschen (Hard Delete)
     * Löscht das RecurringTemplate dauerhaft inklusive aller zugehörigen &#x60;RecurringExceptions&#x60; (Kaskade). Ab dem nächsten &#x60;POST /schedule/generate&#x60; entfällt der Budgetabzug für dieses Template. 
     * @endpoint delete /recurring-templates/{templateId}
     * @param templateId UUID des RecurringTemplate
     */
    deleteRecurringTemplate(templateId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Einzelnes RecurringTemplate abrufen
     * 
     * @endpoint get /recurring-templates/{templateId}
     * @param templateId UUID des RecurringTemplate
     */
    getRecurringTemplate(templateId: string, extraHttpRequestParams?: any): Observable<RecurringTemplateResponse>;

    /**
     * Alle eigenen RecurringTemplates auflisten
     * Gibt alle wiederkehrenden Aufgaben-Vorlagen des eingeloggten Nutzers zurück. RecurringTemplates sind unabhängig von Tasks – sie repräsentieren Aufgaben, die regelmäßig anfallen (z.B. tägliches Stand-up, wöchentlicher Review). Vorkommen erscheinen in &#x60;GET /schedule&#x60; als virtuelle Einträge (&#x60;source: RECURRING&#x60;) und werden nie als ScheduleEntries persistiert. 
     * @endpoint get /recurring-templates
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     */
    listRecurringTemplates(page?: number, size?: number, extraHttpRequestParams?: any): Observable<RecurringTemplatePage>;

    /**
     * RecurringTemplate vollständig aktualisieren
     * Aktualisiert Titel, Dauer, Cognitive Load, Recurrence-Regel oder Startzeit. Bestehende &#x60;RecurringExceptions&#x60; bleiben erhalten und beziehen sich weiterhin auf ihre &#x60;occurrenceDate&#x60;-Einträge. 
     * @endpoint put /recurring-templates/{templateId}
     * @param templateId UUID des RecurringTemplate
     * @param updateRecurringTemplateRequest 
     */
    updateRecurringTemplate(templateId: string, updateRecurringTemplateRequest: UpdateRecurringTemplateRequest, extraHttpRequestParams?: any): Observable<RecurringTemplateResponse>;

}
