/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ProblemDetail } from '../model/problemDetail';
// @ts-ignore
import { RecurringExceptionRequest } from '../model/recurringExceptionRequest';
// @ts-ignore
import { RecurringExceptionResponse } from '../model/recurringExceptionResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    RecurringScheduleServiceInterface
} from './recurringSchedule.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class RecurringScheduleService extends BaseService implements RecurringScheduleServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Ausnahme für ein RecurringTemplate-Vorkommen anlegen
     * Legt eine &#x60;RecurringException&#x60; für ein einzelnes Vorkommen an (Upsert-Semantik). Mögliche Typen: - &#x60;COMPLETED&#x60; – Vorkommen abgehakt. Bleibt als Budgetabzug beim Algorithmus. - &#x60;PINNED&#x60; – Vorkommen fixiert. Erscheint mit &#x60;isPinned: true&#x60;. - &#x60;SKIPPED&#x60; – Vorkommen übersprungen. Kein Budgetabzug beim Algorithmus   (mehr Budget für einmalige Tasks an diesem Tag). - &#x60;RESCHEDULED&#x60; – Vorkommen verschoben auf &#x60;newDate&#x60;/&#x60;newStartTime&#x60;.   Budgetabzug bleibt am ursprünglichen Tag erhalten.  Pro &#x60;(templateId, occurrenceDate)&#x60; existiert maximal eine Exception. Ein erneuter POST überschreibt die bestehende Exception. 
     * @endpoint post /schedule/recurring/{templateId}/exceptions
     * @param templateId UUID des RecurringTemplate
     * @param recurringExceptionRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public createRecurringException(templateId: string, recurringExceptionRequest: RecurringExceptionRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<RecurringExceptionResponse>;
    public createRecurringException(templateId: string, recurringExceptionRequest: RecurringExceptionRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<RecurringExceptionResponse>>;
    public createRecurringException(templateId: string, recurringExceptionRequest: RecurringExceptionRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<RecurringExceptionResponse>>;
    public createRecurringException(templateId: string, recurringExceptionRequest: RecurringExceptionRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (templateId === null || templateId === undefined) {
            throw new Error('Required parameter templateId was null or undefined when calling createRecurringException.');
        }
        if (recurringExceptionRequest === null || recurringExceptionRequest === undefined) {
            throw new Error('Required parameter recurringExceptionRequest was null or undefined when calling createRecurringException.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule/recurring/${this.configuration.encodeParam({name: "templateId", value: templateId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/exceptions`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<RecurringExceptionResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: recurringExceptionRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Ausnahme eines Vorkommens entfernen (Undo)
     * Löscht die &#x60;RecurringException&#x60; – das Vorkommen kehrt zum Normalzustand zurück. - &#x60;COMPLETED&#x60; → erscheint wieder als offen - &#x60;PINNED&#x60; → nicht mehr fixiert - &#x60;SKIPPED&#x60; → erscheint wieder im Plan - &#x60;RESCHEDULED&#x60; → erscheint wieder am ursprünglichen Datum/Zeit 
     * @endpoint delete /schedule/recurring/{templateId}/exceptions/{occurrenceDate}
     * @param templateId UUID des RecurringTemplate
     * @param occurrenceDate Datum des Vorkommens (ISO 8601)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public deleteRecurringException(templateId: string, occurrenceDate: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public deleteRecurringException(templateId: string, occurrenceDate: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public deleteRecurringException(templateId: string, occurrenceDate: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public deleteRecurringException(templateId: string, occurrenceDate: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (templateId === null || templateId === undefined) {
            throw new Error('Required parameter templateId was null or undefined when calling deleteRecurringException.');
        }
        if (occurrenceDate === null || occurrenceDate === undefined) {
            throw new Error('Required parameter occurrenceDate was null or undefined when calling deleteRecurringException.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule/recurring/${this.configuration.encodeParam({name: "templateId", value: templateId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/exceptions/${this.configuration.encodeParam({name: "occurrenceDate", value: occurrenceDate, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "date"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
