/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenerateScheduleRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ScheduleEntry } from '../model/models';
import { ScheduleResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ScheduleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Einmaligen Kalenderblock als erledigt markieren
     * Markiert einen **einmaligen** &#x60;ScheduleEntry&#x60; (&#x60;source: ONE_TIME&#x60;) als erledigt (&#x60;isCompleted &#x3D; true&#x60;).  **Nur für einmalige Tasks (&#x60;source: ONE_TIME&#x60;).** Für wiederkehrende Vorkommen (&#x60;source: RECURRING&#x60;) stattdessen &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60; mit &#x60;type: COMPLETED&#x60; verwenden.  Erledigte Blöcke werden beim erneuten Ausführen des Planungsalgorithmus nicht gelöscht und zählen als fixer Budgetabzug für ihren Tag. 
     * @endpoint patch /schedule/{entryId}/complete
     * @param entryId UUID des ScheduleEntry (Kalenderblocks)
     */
    completeScheduleEntry(entryId: string, extraHttpRequestParams?: any): Observable<ScheduleEntry>;

    /**
     * Planungsalgorithmus ausführen – dynamischer Horizont (synchron)
     * Führt den Planungsalgorithmus **dynamisch** synchron aus. Der Server antwortet erst, wenn der Plan vollständig generiert ist.  **Dynamischer Planungshorizont:** Der Algorithmus startet am &#x60;from&#x60;-Datum und plant einmalige Tasks Tag für Tag vorwärts, bis der Pool leer ist. Das Enddatum (&#x60;to&#x60; in der Response) ergibt sich automatisch aus dem letzten belegten Tag.  **Was der Algorithmus plant (und was nicht):** - **Einmalige Tasks**: werden nach MSTF sortiert und in   verfügbare Zeitslots eingeplant. Erzeugen echte &#x60;ScheduleEntry&#x60;-Objekte   in der DB (&#x60;source: ONE_TIME&#x60;). - **RecurringTemplates**: werden **nicht** eingeplant und erzeugen **keine**   ScheduleEntries. Ihre Dauer pro Tag wird als fixer Budgetabzug behandelt.   Vorkommen erscheinen in &#x60;GET /schedule&#x60; als virtuelle Einträge   (&#x60;source: RECURRING&#x60;) on-the-fly berechnet.  **Sortierung – Minimum Slack Time First (MSTF):** Pro Tag: &#x60;Slack &#x3D; workdaysBetween(heute, deadline) - ceil(restDauer / maxDailyWorkMinutes)&#x60;. Sortierung aufsteigend, Tiebreaker: &#x60;cognitiveLoad&#x60; HIGH zuerst. Tasks ohne Deadline: Slack &#x3D; ∞, werden ans Ende sortiert.  **Budgetabzug pro Tag:** &#x60;maxDailyWorkMinutes&#x60; wird reduziert durch: Completed Entries, Pinned Entries, konfigurierte Pausen und RecurringTemplates (außer Vorkommen mit Exception &#x60;SKIPPED&#x60;).  **Selektives Löschen:** Beim erneuten Generieren werden nur offene, ungepinnte &#x60;ScheduleEntries&#x60; ab &#x60;from&#x60; gelöscht. Completed und Pinned Entries bleiben erhalten.  **Pre-Flight Check:** Fehlen WorkingHours, wird sofort mit &#x60;400 working-hours-missing&#x60; abgebrochen. 
     * @endpoint post /schedule/generate
     * @param generateScheduleRequest 
     */
    generateSchedule(generateScheduleRequest: GenerateScheduleRequest, extraHttpRequestParams?: any): Observable<ScheduleResponse>;

    /**
     * Aktuellen Plan für einen Zeitraum abrufen
     * Gibt den Plan für den angegebenen Zeitraum als **unified Response** zurück. Die Antwort enthält zwei Arten von Einträgen, erkennbar am &#x60;source&#x60;-Feld:  - &#x60;source: ONE_TIME&#x60; – echte &#x60;ScheduleEntry&#x60;-Objekte aus der Datenbank   (einmalige Tasks). Das Feld &#x60;entryId&#x60; ist gesetzt und wird für   PATCH-Aktionen (complete, pin, unpin) benötigt.  - &#x60;source: RECURRING&#x60; – virtuelle Vorkommen, server-seitig on-the-fly   aus &#x60;RecurringTemplate&#x60;-Regeln berechnet. Kein DB-Eintrag –   stattdessen sind &#x60;templateId&#x60; und &#x60;occurrenceDate&#x60; gesetzt.   Aktionen über &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60;.  Beide Typen werden nach Datum und Uhrzeit sortiert zurückgegeben. 
     * @endpoint get /schedule
     * @param from Startdatum (ISO 8601)
     * @param to Enddatum (ISO 8601)
     */
    getSchedule(from: string, to: string, extraHttpRequestParams?: any): Observable<ScheduleResponse>;

    /**
     * Einmaligen Kalenderblock fixieren (pinnen)
     * Setzt &#x60;isPinned &#x3D; true&#x60; auf einem **einmaligen** &#x60;ScheduleEntry&#x60; (&#x60;source: ONE_TIME&#x60;).  **Nur für einmalige Tasks (&#x60;source: ONE_TIME&#x60;).** Für wiederkehrende Vorkommen (&#x60;source: RECURRING&#x60;) stattdessen &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60; mit &#x60;type: PINNED&#x60; verwenden.  Gepinnte Blöcke werden beim erneuten Ausführen des Algorithmus nicht überschrieben und zählen als fixer Budgetabzug. Ermöglicht manuelles Verschieben via Drag &amp; Drop. Entpinnen über &#x60;PATCH /schedule/{entryId}/unpin&#x60;. 
     * @endpoint patch /schedule/{entryId}/pin
     * @param entryId UUID des ScheduleEntry (Kalenderblocks)
     */
    pinScheduleEntry(entryId: string, extraHttpRequestParams?: any): Observable<ScheduleEntry>;

    /**
     * Fixierung eines Kalenderblocks aufheben
     * Setzt &#x60;isPinned &#x3D; false&#x60; auf einem &#x60;ScheduleEntry&#x60;. Der Block kann beim nächsten Ausführen des Planungsalgorithmus wieder überschrieben oder verschoben werden. 
     * @endpoint patch /schedule/{entryId}/unpin
     * @param entryId UUID des ScheduleEntry (Kalenderblocks)
     */
    unpinScheduleEntry(entryId: string, extraHttpRequestParams?: any): Observable<ScheduleEntry>;

}
