/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { GenerateScheduleRequest } from '../model/generateScheduleRequest';
// @ts-ignore
import { ProblemDetail } from '../model/problemDetail';
// @ts-ignore
import { ScheduleEntry } from '../model/scheduleEntry';
// @ts-ignore
import { ScheduleResponse } from '../model/scheduleResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    ScheduleServiceInterface
} from './schedule.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class ScheduleService extends BaseService implements ScheduleServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Einmaligen Kalenderblock als erledigt markieren
     * Markiert einen **einmaligen** &#x60;ScheduleEntry&#x60; (&#x60;source: ONE_TIME&#x60;) als erledigt (&#x60;isCompleted &#x3D; true&#x60;).  **Nur für einmalige Tasks (&#x60;source: ONE_TIME&#x60;).** Für wiederkehrende Vorkommen (&#x60;source: RECURRING&#x60;) stattdessen &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60; mit &#x60;type: COMPLETED&#x60; verwenden.  Erledigte Blöcke werden beim erneuten Ausführen des Planungsalgorithmus nicht gelöscht und zählen als fixer Budgetabzug für ihren Tag. 
     * @endpoint patch /schedule/{entryId}/complete
     * @param entryId UUID des ScheduleEntry (Kalenderblocks)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public completeScheduleEntry(entryId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<ScheduleEntry>;
    public completeScheduleEntry(entryId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ScheduleEntry>>;
    public completeScheduleEntry(entryId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ScheduleEntry>>;
    public completeScheduleEntry(entryId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling completeScheduleEntry.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule/${this.configuration.encodeParam({name: "entryId", value: entryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/complete`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ScheduleEntry>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Planungsalgorithmus ausführen – dynamischer Horizont (synchron)
     * Führt den Planungsalgorithmus **dynamisch** synchron aus. Der Server antwortet erst, wenn der Plan vollständig generiert ist.  **Dynamischer Planungshorizont:** Der Algorithmus startet am &#x60;from&#x60;-Datum und plant einmalige Tasks Tag für Tag vorwärts, bis der Pool leer ist. Das Enddatum (&#x60;to&#x60; in der Response) ergibt sich automatisch aus dem letzten belegten Tag.  **Was der Algorithmus plant (und was nicht):** - **Einmalige Tasks**: werden nach MSTF sortiert und in   verfügbare Zeitslots eingeplant. Erzeugen echte &#x60;ScheduleEntry&#x60;-Objekte   in der DB (&#x60;source: ONE_TIME&#x60;). - **RecurringTemplates**: werden **nicht** eingeplant und erzeugen **keine**   ScheduleEntries. Ihre Dauer pro Tag wird als fixer Budgetabzug behandelt.   Vorkommen erscheinen in &#x60;GET /schedule&#x60; als virtuelle Einträge   (&#x60;source: RECURRING&#x60;) on-the-fly berechnet.  **Sortierung – Minimum Slack Time First (MSTF):** Pro Tag: &#x60;Slack &#x3D; workdaysBetween(heute, deadline) - ceil(restDauer / maxDailyWorkMinutes)&#x60;. Sortierung aufsteigend, Tiebreaker: &#x60;cognitiveLoad&#x60; HIGH zuerst. Tasks ohne Deadline: Slack &#x3D; ∞, werden ans Ende sortiert.  **Budgetabzug pro Tag:** &#x60;maxDailyWorkMinutes&#x60; wird reduziert durch: Completed Entries, Pinned Entries, konfigurierte Pausen und RecurringTemplates (außer Vorkommen mit Exception &#x60;SKIPPED&#x60;).  **Selektives Löschen:** Beim erneuten Generieren werden nur offene, ungepinnte &#x60;ScheduleEntries&#x60; ab &#x60;from&#x60; gelöscht. Completed und Pinned Entries bleiben erhalten.  **Pre-Flight Check:** Fehlen WorkingHours, wird sofort mit &#x60;400 working-hours-missing&#x60; abgebrochen. 
     * @endpoint post /schedule/generate
     * @param generateScheduleRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public generateSchedule(generateScheduleRequest: GenerateScheduleRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<ScheduleResponse>;
    public generateSchedule(generateScheduleRequest: GenerateScheduleRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ScheduleResponse>>;
    public generateSchedule(generateScheduleRequest: GenerateScheduleRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ScheduleResponse>>;
    public generateSchedule(generateScheduleRequest: GenerateScheduleRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (generateScheduleRequest === null || generateScheduleRequest === undefined) {
            throw new Error('Required parameter generateScheduleRequest was null or undefined when calling generateSchedule.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule/generate`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ScheduleResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: generateScheduleRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Aktuellen Plan für einen Zeitraum abrufen
     * Gibt den Plan für den angegebenen Zeitraum als **unified Response** zurück. Die Antwort enthält zwei Arten von Einträgen, erkennbar am &#x60;source&#x60;-Feld:  - &#x60;source: ONE_TIME&#x60; – echte &#x60;ScheduleEntry&#x60;-Objekte aus der Datenbank   (einmalige Tasks). Das Feld &#x60;entryId&#x60; ist gesetzt und wird für   PATCH-Aktionen (complete, pin, unpin) benötigt.  - &#x60;source: RECURRING&#x60; – virtuelle Vorkommen, server-seitig on-the-fly   aus &#x60;RecurringTemplate&#x60;-Regeln berechnet. Kein DB-Eintrag –   stattdessen sind &#x60;templateId&#x60; und &#x60;occurrenceDate&#x60; gesetzt.   Aktionen über &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60;.  Beide Typen werden nach Datum und Uhrzeit sortiert zurückgegeben. 
     * @endpoint get /schedule
     * @param from Startdatum (ISO 8601)
     * @param to Enddatum (ISO 8601)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getSchedule(from: string, to: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<ScheduleResponse>;
    public getSchedule(from: string, to: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ScheduleResponse>>;
    public getSchedule(from: string, to: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ScheduleResponse>>;
    public getSchedule(from: string, to: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (from === null || from === undefined) {
            throw new Error('Required parameter from was null or undefined when calling getSchedule.');
        }
        if (to === null || to === undefined) {
            throw new Error('Required parameter to was null or undefined when calling getSchedule.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'from',
            <any>from,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'to',
            <any>to,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ScheduleResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Einmaligen Kalenderblock fixieren (pinnen)
     * Setzt &#x60;isPinned &#x3D; true&#x60; auf einem **einmaligen** &#x60;ScheduleEntry&#x60; (&#x60;source: ONE_TIME&#x60;).  **Nur für einmalige Tasks (&#x60;source: ONE_TIME&#x60;).** Für wiederkehrende Vorkommen (&#x60;source: RECURRING&#x60;) stattdessen &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60; mit &#x60;type: PINNED&#x60; verwenden.  Gepinnte Blöcke werden beim erneuten Ausführen des Algorithmus nicht überschrieben und zählen als fixer Budgetabzug. Ermöglicht manuelles Verschieben via Drag &amp; Drop. Entpinnen über &#x60;PATCH /schedule/{entryId}/unpin&#x60;. 
     * @endpoint patch /schedule/{entryId}/pin
     * @param entryId UUID des ScheduleEntry (Kalenderblocks)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public pinScheduleEntry(entryId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<ScheduleEntry>;
    public pinScheduleEntry(entryId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ScheduleEntry>>;
    public pinScheduleEntry(entryId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ScheduleEntry>>;
    public pinScheduleEntry(entryId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling pinScheduleEntry.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule/${this.configuration.encodeParam({name: "entryId", value: entryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/pin`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ScheduleEntry>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Fixierung eines Kalenderblocks aufheben
     * Setzt &#x60;isPinned &#x3D; false&#x60; auf einem &#x60;ScheduleEntry&#x60;. Der Block kann beim nächsten Ausführen des Planungsalgorithmus wieder überschrieben oder verschoben werden. 
     * @endpoint patch /schedule/{entryId}/unpin
     * @param entryId UUID des ScheduleEntry (Kalenderblocks)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public unpinScheduleEntry(entryId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<ScheduleEntry>;
    public unpinScheduleEntry(entryId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ScheduleEntry>>;
    public unpinScheduleEntry(entryId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ScheduleEntry>>;
    public unpinScheduleEntry(entryId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling unpinScheduleEntry.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schedule/${this.configuration.encodeParam({name: "entryId", value: entryId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/unpin`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ScheduleEntry>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
