/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenerateScheduleRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ScheduleResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ScheduleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Planungsalgorithmus ausführen (synchron)
     * Führt den Planungsalgorithmus für den angegebenen Zeitraum synchron aus. Der Server antwortet erst, wenn der Plan vollständig generiert ist.  **Algorithmus-Prinzipien (aus Anforderungsdokument):** - Max. ~4h kognitive Arbeit pro Tag (konfigurierbar via &#x60;maxDailyWorkMinutes&#x60;) - Aufgaben werden nach &#x60;cognitiveLoad&#x60; und &#x60;deadline&#x60; priorisiert - Pausen des Nutzers werden berücksichtigt und blockiert - Tasks länger als ein Arbeitstag werden automatisch gesplittet  Der generierte Plan überschreibt den vorherigen Plan für denselben Zeitraum. 
     * @endpoint post /schedule/generate
     * @param generateScheduleRequest 
     */
    generateSchedule(generateScheduleRequest: GenerateScheduleRequest, extraHttpRequestParams?: any): Observable<ScheduleResponse>;

    /**
     * Aktuellen Plan für einen Zeitraum abrufen
     * Gibt den zuletzt generierten Plan für den angegebenen Zeitraum zurück. Enthält sowohl Tasks als auch Pausen als &#x60;ScheduleEntry&#x60;-Objekte. 
     * @endpoint get /schedule
     * @param from Startdatum (ISO 8601)
     * @param to Enddatum (ISO 8601)
     */
    getSchedule(from: string, to: string, extraHttpRequestParams?: any): Observable<ScheduleResponse>;

}
