/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTaskRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { TaskPage } from '../model/models';
import { TaskResponse } from '../model/models';
import { TaskStatus } from '../model/models';
import { UpdateTaskRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TasksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Task global als erledigt markieren (Backlog-Ansicht)
     * Setzt den Status des Tasks auf &#x60;DONE&#x60; und setzt &#x60;completedAt&#x60;.  Einmalige Tasks können hierüber dauerhaft als erledigt markiert werden. Für wiederkehrende Aufgaben existiert kein &#x60;Task&#x60;-Objekt mehr – einzelne Vorkommen werden über &#x60;POST /schedule/recurring/{templateId}/exceptions&#x60; mit &#x60;type: COMPLETED&#x60; abgehakt.  Dieser Endpunkt ist primär für die **Backlog-Ansicht** gedacht (z.B. um einen Task manuell zu schließen, ohne ihn im Tagesplan abzuhaken). 
     * @endpoint patch /tasks/{taskId}/complete
     * @param taskId UUID des Tasks
     */
    completeTask(taskId: string, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Neuen Task erstellen
     * Erstellt einen neuen Task für den eingeloggten Nutzer. Wenn &#x60;estimatedDurationMinutes&#x60; &gt; 480 (8h), wird empfohlen, den Task zu splitten – dies kann entweder clientseitig angeboten oder serverseitig automatisch erfolgen.  **Einschränkung:** &#x60;SUPER_ADMIN&#x60;-Nutzer dürfen keine Tasks erstellen (&#x60;403 Forbidden&#x60;). Tasks können ausschließlich von &#x60;USER&#x60;- und &#x60;ADMIN&#x60;-Nutzern angelegt werden. 
     * @endpoint post /tasks
     * @param createTaskRequest 
     */
    createTask(createTaskRequest: CreateTaskRequest, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Task löschen (Hard Delete)
     * 
     * @endpoint delete /tasks/{taskId}
     * @param taskId UUID des Tasks
     */
    deleteTask(taskId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Einzelnen Task abrufen
     * 
     * @endpoint get /tasks/{taskId}
     * @param taskId UUID des Tasks
     */
    getTask(taskId: string, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Eigene Tasks auflisten
     * Gibt paginiert alle Tasks des eingeloggten Nutzers zurück. Filterbar nach Status und Deadline-Zeitraum. 
     * @endpoint get /tasks
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     * @param status Nur Tasks mit diesem Status zurückgeben
     * @param from Nur Tasks mit Deadline ab diesem Datum (ISO 8601 Date)
     * @param to Nur Tasks mit Deadline bis zu diesem Datum (ISO 8601 Date)
     */
    listTasks(page?: number, size?: number, status?: TaskStatus, from?: string, to?: string, extraHttpRequestParams?: any): Observable<TaskPage>;

    /**
     * Erledigten Task wieder öffnen
     * Setzt den Status des Tasks von DONE zurück auf OPEN.
     * @endpoint patch /tasks/{taskId}/reopen
     * @param taskId UUID des Tasks
     */
    reopenTask(taskId: string, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Task vollständig aktualisieren
     * 
     * @endpoint put /tasks/{taskId}
     * @param taskId UUID des Tasks
     * @param updateTaskRequest 
     */
    updateTask(taskId: string, updateTaskRequest: UpdateTaskRequest, extraHttpRequestParams?: any): Observable<TaskResponse>;

}
