/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTaskRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { TaskPage } from '../model/models';
import { TaskResponse } from '../model/models';
import { TaskStatus } from '../model/models';
import { UpdateTaskRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TasksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Task als erledigt markieren
     * Setzt den Status des Tasks auf DONE und setzt completedAt.
     * @endpoint patch /tasks/{taskId}/complete
     * @param taskId UUID des Tasks
     */
    completeTask(taskId: string, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Neuen Task erstellen
     * Erstellt einen neuen Task für den eingeloggten Nutzer. Wenn &#x60;estimatedDurationMinutes&#x60; &gt; 480 (8h), wird empfohlen, den Task zu splitten – dies kann entweder clientseitig angeboten oder serverseitig automatisch erfolgen. 
     * @endpoint post /tasks
     * @param createTaskRequest 
     */
    createTask(createTaskRequest: CreateTaskRequest, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Task löschen (Hard Delete)
     * 
     * @endpoint delete /tasks/{taskId}
     * @param taskId UUID des Tasks
     */
    deleteTask(taskId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Einzelnen Task abrufen
     * 
     * @endpoint get /tasks/{taskId}
     * @param taskId UUID des Tasks
     */
    getTask(taskId: string, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Eigene Tasks auflisten
     * Gibt paginiert alle Tasks des eingeloggten Nutzers zurück. Filterbar nach Status und Deadline-Zeitraum. 
     * @endpoint get /tasks
     * @param page Seitennummer (0-basiert)
     * @param size Anzahl Einträge pro Seite
     * @param status Nur Tasks mit diesem Status zurückgeben
     * @param from Nur Tasks mit Deadline ab diesem Datum (ISO 8601 Date)
     * @param to Nur Tasks mit Deadline bis zu diesem Datum (ISO 8601 Date)
     */
    listTasks(page?: number, size?: number, status?: TaskStatus, from?: string, to?: string, extraHttpRequestParams?: any): Observable<TaskPage>;

    /**
     * Erledigten Task wieder öffnen
     * Setzt den Status des Tasks von DONE zurück auf OPEN.
     * @endpoint patch /tasks/{taskId}/reopen
     * @param taskId UUID des Tasks
     */
    reopenTask(taskId: string, extraHttpRequestParams?: any): Observable<TaskResponse>;

    /**
     * Task vollständig aktualisieren
     * 
     * @endpoint put /tasks/{taskId}
     * @param taskId UUID des Tasks
     * @param updateTaskRequest 
     */
    updateTask(taskId: string, updateTaskRequest: UpdateTaskRequest, extraHttpRequestParams?: any): Observable<TaskResponse>;

}
