/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';
import { UpdateUserRequest } from '../model/models';
import { UserResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Eigenen Account löschen (Hard Delete)
     * Löscht den eigenen Account inklusive aller zugehörigen Daten (Tasks, Breaks, Schedule-Einträge).  **Einschränkungen:** - &#x60;SUPER_ADMIN&#x60; kann sich nicht selbst löschen (&#x60;403 Forbidden&#x60;). - Ein &#x60;ADMIN&#x60;, der der letzte Admin seiner Organisation ist, kann sich nicht selbst löschen (&#x60;409 Conflict&#x60;).   Es muss mindestens ein weiterer Admin in der Organisation verbleiben. 
     * @endpoint delete /users/me
     */
    deleteMyAccount(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Eigenes Profil abrufen
     * 
     * @endpoint get /users/me
     */
    getMyProfile(extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Eigenes Profil aktualisieren
     * 
     * @endpoint put /users/me
     * @param updateUserRequest 
     */
    updateMyProfile(updateUserRequest: UpdateUserRequest, extraHttpRequestParams?: any): Observable<UserResponse>;

}
