/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';
import { UpsertWorkingHoursRequest } from '../model/models';
import { WorkingHoursResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WorkingHoursServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Eigene Arbeitszeit-Vorlage abrufen
     * Gibt die wöchentliche Arbeitszeit-Vorlage des eingeloggten Nutzers zurück. Die Vorlage enthält für jeden Wochentag (Mo–So) einen Eintrag mit Start-/Endzeit oder die Markierung als arbeitsfreier Tag.  Falls noch keine Vorlage gespeichert wurde, wird &#x60;404&#x60; zurückgegeben. 
     * @endpoint get /users/me/working-hours
     */
    getWorkingHours(extraHttpRequestParams?: any): Observable<WorkingHoursResponse>;

    /**
     * Eigene Arbeitszeit-Vorlage speichern oder ersetzen
     * Speichert die wöchentliche Arbeitszeit-Vorlage des eingeloggten Nutzers vollständig. Eine bestehende Vorlage wird dabei atomar ersetzt – es gibt keinen Teilupdate.  **Regeln:** - Das Array &#x60;days&#x60; muss **alle 7 Wochentage** (Mo–So) enthalten, jeder genau einmal. - Für Arbeitstage (&#x60;isWorkDay: true&#x60;) sind &#x60;startTime&#x60; und &#x60;endTime&#x60; **Pflichtfelder**. - Für freie Tage (&#x60;isWorkDay: false&#x60;) werden &#x60;startTime&#x60; und &#x60;endTime&#x60; ignoriert bzw.   müssen nicht angegeben werden. - &#x60;endTime&#x60; muss nach &#x60;startTime&#x60; liegen (Validierung serverseitig). - Pausen werden **separat** über &#x60;/breaks&#x60; konfiguriert und nicht hier eingetragen.  Der Planungsalgorithmus (&#x60;/schedule/generate&#x60;) nutzt diese Vorlage automatisch, um den täglichen Arbeitsrahmen zu bestimmen. 
     * @endpoint put /users/me/working-hours
     * @param upsertWorkingHoursRequest 
     */
    upsertWorkingHours(upsertWorkingHoursRequest: UpsertWorkingHoursRequest, extraHttpRequestParams?: any): Observable<WorkingHoursResponse>;

}
