/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ProblemDetail } from '../model/problemDetail';
// @ts-ignore
import { UpsertWorkingHoursRequest } from '../model/upsertWorkingHoursRequest';
// @ts-ignore
import { WorkingHoursResponse } from '../model/workingHoursResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    WorkingHoursServiceInterface
} from './workingHours.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class WorkingHoursService extends BaseService implements WorkingHoursServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Eigene Arbeitszeit-Vorlage abrufen
     * Gibt die wöchentliche Arbeitszeit-Vorlage des eingeloggten Nutzers zurück. Die Vorlage enthält für jeden Wochentag (Mo–So) einen Eintrag mit Start-/Endzeit oder die Markierung als arbeitsfreier Tag.  Falls noch keine Vorlage gespeichert wurde, wird &#x60;404&#x60; zurückgegeben. 
     * @endpoint get /users/me/working-hours
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getWorkingHours(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<WorkingHoursResponse>;
    public getWorkingHours(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkingHoursResponse>>;
    public getWorkingHours(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkingHoursResponse>>;
    public getWorkingHours(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/users/me/working-hours`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkingHoursResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Eigene Arbeitszeit-Vorlage speichern oder ersetzen
     * Speichert die wöchentliche Arbeitszeit-Vorlage des eingeloggten Nutzers vollständig. Eine bestehende Vorlage wird dabei atomar ersetzt – es gibt keinen Teilupdate.  **Regeln:** - Das Array &#x60;days&#x60; muss **alle 7 Wochentage** (Mo–So) enthalten, jeder genau einmal. - Für Arbeitstage (&#x60;isWorkDay: true&#x60;) sind &#x60;startTime&#x60; und &#x60;endTime&#x60; **Pflichtfelder**. - Für freie Tage (&#x60;isWorkDay: false&#x60;) werden &#x60;startTime&#x60; und &#x60;endTime&#x60; ignoriert bzw.   müssen nicht angegeben werden. - &#x60;endTime&#x60; muss nach &#x60;startTime&#x60; liegen (Validierung serverseitig). - Pausen werden **separat** über &#x60;/breaks&#x60; konfiguriert und nicht hier eingetragen.  Der Planungsalgorithmus (&#x60;/schedule/generate&#x60;) nutzt diese Vorlage automatisch, um den täglichen Arbeitsrahmen zu bestimmen. 
     * @endpoint put /users/me/working-hours
     * @param upsertWorkingHoursRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public upsertWorkingHours(upsertWorkingHoursRequest: UpsertWorkingHoursRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<WorkingHoursResponse>;
    public upsertWorkingHours(upsertWorkingHoursRequest: UpsertWorkingHoursRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WorkingHoursResponse>>;
    public upsertWorkingHours(upsertWorkingHoursRequest: UpsertWorkingHoursRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WorkingHoursResponse>>;
    public upsertWorkingHours(upsertWorkingHoursRequest: UpsertWorkingHoursRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (upsertWorkingHoursRequest === null || upsertWorkingHoursRequest === undefined) {
            throw new Error('Required parameter upsertWorkingHoursRequest was null or undefined when calling upsertWorkingHours.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/users/me/working-hours`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WorkingHoursResponse>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: upsertWorkingHoursRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
