/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddSuperAdminRequest { 
    /**
     * E-Mail eines bestehenden Nutzers, der Super-Admin werden soll
     */
    email: string;
}

