/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddSuperAdminRequest { 
    /**
     * E-Mail-Adresse der einzuladenden Person. Es wird eine Einladungs-E-Mail verschickt – kein bestehender Account erforderlich.
     */
    email: string;
}

