/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';
import { BreakType } from './breakType';


export interface BreakResponse { 
    id: string;
    label: string;
    /**
     * Uhrzeit im Format HH:mm
     */
    startTime: string;
    /**
     * Uhrzeit im Format HH:mm
     */
    endTime: string;
    breakType: BreakType;
    recurrence?: RecurrenceRule;
    /**
     * Nur gesetzt wenn breakType = ONE_TIME. Datum des einmaligen Vorkommens. 
     */
    date?: string | null;
    /**
     * Nur gesetzt wenn breakType = BOUNDED_RECURRING. Erster Tag, an dem die Pause gilt (inklusiv). 
     */
    validFrom?: string | null;
    /**
     * Nur gesetzt wenn breakType = BOUNDED_RECURRING. Letzter Tag, an dem die Pause gilt (inklusiv). 
     */
    validUntil?: string | null;
}
export namespace BreakResponse {
}


