/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';


export interface BreakResponse { 
    id: string;
    label: string;
    /**
     * Uhrzeit im Format HH:mm
     */
    startTime: string;
    /**
     * Uhrzeit im Format HH:mm
     */
    endTime: string;
    recurrence: RecurrenceRule;
}

