/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Kognitive Belastung der Aufgabe (aus Anforderungsdokument: \"Wie fordernd ist die Aufgabe?\"): - `LOW`: Routine / stupide Aufgabe (z.B. E-Mails sortieren) - `MEDIUM`: Normaler Arbeitsaufwand - `HIGH`: Höchste Konzentration erforderlich (z.B. komplexe Analyse)  Der Planungsalgorithmus nutzt dieses Feld um `HIGH`-Tasks bevorzugt in produktive Morgenstunden einzuplanen. 
 */
export const CognitiveLoad = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type CognitiveLoad = typeof CognitiveLoad[keyof typeof CognitiveLoad];

