/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CognitiveLoad } from './cognitiveLoad';


export interface CreateTaskRequest { 
    title: string;
    description?: string | null;
    cognitiveLoad: CognitiveLoad;
    /**
     * Geschätzte Arbeitsdauer in Minuten. Bei > 480 (8h) empfiehlt das System Splitting.
     */
    estimatedDurationMinutes: number;
    deadline?: string | null;
    /**
     * Frühestes Startdatum (optional). Der Algorithmus plant den Task nicht vor diesem Datum ein.
     */
    startDate?: string | null;
}
export namespace CreateTaskRequest {
}


