/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';


export interface CreateBreakRequest { 
    label: string;
    startTime: string;
    endTime: string;
    recurrence: RecurrenceRule;
}

