/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrganizationRequest { 
    name: string;
    /**
     * E-Mail des ersten Admins. Er erhält automatisch eine Einladungs-E-Mail.
     */
    adminEmail: string;
}

