/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';
import { CognitiveLoad } from './cognitiveLoad';


export interface CreateRecurringTemplateRequest { 
    title: string;
    description?: string | null;
    cognitiveLoad: CognitiveLoad;
    /**
     * Dauer eines Vorkommens in Minuten
     */
    durationMinutes: number;
    recurrenceRule: RecurrenceRule;
    /**
     * Bevorzugte Startzeit (optional)
     */
    preferredStartTime?: string | null;
}
export namespace CreateRecurringTemplateRequest {
}


