/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Validierungsfehler für ein einzelnes Feld
 */
export interface FieldError { 
    field: string;
    message: string;
}

