/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateScheduleRequest { 
    /**
     * Startdatum des zu planenden Zeitraums
     */
    from: string;
    /**
     * Enddatum des zu planenden Zeitraums
     */
    to: string;
    /**
     * Maximale kognitive Arbeitszeit pro Tag in Minuten. Default: 240 (4h, basierend auf wissenschaftlicher Empfehlung aus Anforderungsdokument)
     */
    maxDailyWorkMinutes?: number;
}

