/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateScheduleRequest { 
    /**
     * Startdatum der Planung (ISO 8601). Der Algorithmus plant ab diesem Datum so viele Tage wie nötig, bis alle einmaligen Tasks eingeplant sind. Das Enddatum ergibt sich dynamisch aus der Response (`to`-Feld). Empfehlung: Montag, damit vollständige Wochen geplant werden. 
     */
    from: string;
    /**
     * Maximale kognitive Arbeitszeit pro Tag in Minuten (Default: 240 = 4h). RecurringTemplate-Dauer wird zusätzlich abgezogen – das effektive Budget für einmalige Tasks kann also kleiner sein. 
     */
    maxDailyWorkMinutes?: number;
}

