/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateScheduleRequest { 
    /**
     * Startdatum des zu planenden Zeitraums (ISO 8601). Empfehlung: immer ein Montag, damit der Algorithmus vollständige Wochen plant. 
     */
    from: string;
    /**
     * Enddatum des zu planenden Zeitraums (ISO 8601). Der Zeitraum beträgt **immer genau 14 Tage** (`from` + 13 Tage). Kürzere oder längere Fenster werden serverseitig mit `400` abgelehnt. 
     */
    to: string;
    /**
     * Maximale kognitive Arbeitszeit pro Tag in Minuten. Default: 240 (4h, basierend auf wissenschaftlicher Empfehlung aus Anforderungsdokument)
     */
    maxDailyWorkMinutes?: number;
}

