/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './userResponse';


export interface LoginResponse { 
    /**
     * JWT Access Token, gültig 15 Minuten
     */
    accessToken: string;
    /**
     * Refresh Token, gültig 7 Tage
     */
    refreshToken: string;
    user: UserResponse;
}

