/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Paginierungsmetadaten, enthalten in allen paginierten Antworten
 */
export interface PageMetadata { 
    /**
     * Aktuelle Seitennummer (0-basiert)
     */
    page: number;
    /**
     * Einträge pro Seite
     */
    size: number;
    /**
     * Gesamtanzahl aller Einträge
     */
    totalElements: number;
    /**
     * Gesamtanzahl der Seiten
     */
    totalPages: number;
}

