/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceType } from './recurrenceType';


/**
 * Wiederholungsregel für Tasks und Pausen.  **Aktuelles Modell (MVP):** Typ + Intervall Beispiele: - `{ \"type\": \"DAILY\", \"interval\": 1 }` → jeden Tag - `{ \"type\": \"WEEKLY\", \"interval\": 2 }` → alle 2 Wochen - `{ \"type\": \"MONTHLY\", \"interval\": 1 }` → jeden Monat  **Erweiterbarkeit:** Das Modell ist so strukturiert, dass es in einer späteren Version um ein `rrule`-Feld (iCal RRULE-Standard) ergänzt werden kann, ohne bestehende Clients zu brechen. 
 */
export interface RecurrenceRule { 
    type: RecurrenceType;
    /**
     * Alle N Einheiten wiederholen (abhängig von type)
     */
    interval: number;
}
export namespace RecurrenceRule {
}


