/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurringExceptionType } from './recurringExceptionType';


export interface RecurringExceptionRequest { 
    /**
     * Datum des konkreten Vorkommens, für das die Ausnahme gilt
     */
    occurrenceDate: string;
    type: RecurringExceptionType;
    /**
     * Nur bei type = RESCHEDULED: neues Datum des Vorkommens
     */
    newDate?: string | null;
    /**
     * Nur bei type = RESCHEDULED: neue Startzeit
     */
    newStartTime?: string | null;
}
export namespace RecurringExceptionRequest {
}


