/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Art der Ausnahme für ein RecurringTemplate-Vorkommen: - `COMPLETED`: Vorkommen abgehakt. Bleibt als Budgetabzug erhalten. - `PINNED`: Vorkommen fixiert. Erscheint mit `isPinned: true`. - `SKIPPED`: Vorkommen übersprungen. Kein Budgetabzug beim Algorithmus. - `RESCHEDULED`: Vorkommen verschoben auf `newDate`/`newStartTime`.   Budgetabzug bleibt am ursprünglichen Tag erhalten. 
 */
export const RecurringExceptionType = {
    Completed: 'COMPLETED',
    Pinned: 'PINNED',
    Skipped: 'SKIPPED',
    Rescheduled: 'RESCHEDULED'
} as const;
export type RecurringExceptionType = typeof RecurringExceptionType[keyof typeof RecurringExceptionType];

