/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurringExceptionType } from './recurringExceptionType';


export interface RecurringExceptionResponse { 
    id: string;
    templateId: string;
    occurrenceDate: string;
    type: RecurringExceptionType;
    newDate?: string | null;
    newStartTime?: string | null;
    createdAt: string;
}
export namespace RecurringExceptionResponse {
}


