/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';
import { CognitiveLoad } from './cognitiveLoad';


/**
 * Eine wiederkehrende Aufgaben-Vorlage. Vorkommen werden on-the-fly berechnet und nie persistiert.
 */
export interface RecurringTemplateResponse { 
    id: string;
    title: string;
    description?: string | null;
    cognitiveLoad: CognitiveLoad;
    /**
     * Dauer eines Vorkommens in Minuten
     */
    durationMinutes: number;
    recurrenceRule: RecurrenceRule;
    /**
     * Bevorzugte Startzeit (optional). Wird von GET /schedule für die Zeitdarstellung genutzt.
     */
    preferredStartTime?: string | null;
    ownerId: string;
    organizationId: string;
    createdAt: string;
    updatedAt: string;
}
export namespace RecurringTemplateResponse {
}


