/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshResponse { 
    /**
     * Neuer JWT Access Token, gültig 15 Minuten
     */
    accessToken: string;
    /**
     * Neuer Refresh Token (Token Rotation), gültig 7 Tage
     */
    refreshToken: string;
}

