/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Nutzerrollen (RBAC): - `SUPER_ADMIN`: Plattformweite Verwaltung (Organisationen erstellen/löschen, Super-Admins ernennen) - `ADMIN`: Verwaltung der eigenen Organisation (Mitglieder, Einladungen, Einstellungen) - `USER`: Standard-Nutzer (eigene Tasks und Planung) 
 */
export const Role = {
    SuperAdmin: 'SUPER_ADMIN',
    Admin: 'ADMIN',
    User: 'USER'
} as const;
export type Role = typeof Role[keyof typeof Role];

