/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ein eingeplanter Zeitblock im Plan (Task-Block oder Pause)
 */
export interface ScheduleEntry { 
    date: string;
    startTime: string;
    endTime: string;
    type: ScheduleEntry.TypeEnum;
    /**
     * Gesetzt wenn type = TASK
     */
    taskId?: string | null;
    /**
     * Gesetzt wenn type = TASK (Convenience-Feld)
     */
    taskTitle?: string | null;
    /**
     * Gesetzt wenn type = BREAK
     */
    breakId?: string | null;
    /**
     * Gesetzt wenn type = BREAK (Convenience-Feld)
     */
    breakLabel?: string | null;
}
export namespace ScheduleEntry {
    export const TypeEnum = {
        Task: 'TASK',
        Break: 'BREAK'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


