/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleEntry } from './scheduleEntry';


export interface ScheduleResponse { 
    /**
     * Zeitstempel der letzten Plan-Generierung
     */
    generatedAt: string;
    from: string;
    to: string;
    /**
     * Summe aller eingeplanten Arbeitsminuten im Zeitraum
     */
    totalWorkMinutes: number;
    entries: Array<ScheduleEntry>;
}

