/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ein eingeplanter Zeitblock im Plan (Task-Block oder Pause)
 */
export interface ScheduleEntry { 
    /**
     * Eindeutige ID dieses Kalenderblocks. Wird für PATCH /schedule/{entryId}/complete und /pin benötigt.
     */
    id: string;
    date: string;
    startTime: string;
    endTime: string;
    type: ScheduleEntry.TypeEnum;
    /**
     * Gibt an, ob dieser spezifische Kalenderblock abgehakt wurde. Wird über `PATCH /schedule/{entryId}/complete` gesetzt. Bei wiederkehrenden Tasks: nur dieser Block ist erledigt, der Haupt-Task und zukünftige Blöcke bleiben unverändert. 
     */
    isCompleted: boolean;
    /**
     * Gibt an, ob dieser Block manuell fixiert wurde (`PATCH /schedule/{entryId}/pin`). Gepinnte Blöcke werden beim erneuten Ausführen des Planungsalgorithmus **nicht** überschrieben – sie blockieren weiterhin die entsprechende Zeit. 
     */
    isPinned: boolean;
    /**
     * Gesetzt wenn type = TASK
     */
    taskId?: string | null;
    /**
     * Gesetzt wenn type = TASK (Convenience-Feld)
     */
    taskTitle?: string | null;
    /**
     * Gesetzt wenn type = BREAK
     */
    breakId?: string | null;
    /**
     * Gesetzt wenn type = BREAK (Convenience-Feld)
     */
    breakLabel?: string | null;
}
export namespace ScheduleEntry {
    export const TypeEnum = {
        Task: 'TASK',
        Break: 'BREAK'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


