/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleEntry } from './scheduleEntry';


export interface ScheduleResponse { 
    /**
     * Zeitstempel der letzten Plan-Generierung
     */
    generatedAt: string;
    from: string;
    /**
     * Letzter tatsächlich eingeplanter Tag. Wird dynamisch vom Algorithmus bestimmt.
     */
    to: string;
    /**
     * Summe aller eingeplanten Arbeitsminuten im Zeitraum
     */
    totalWorkMinutes: number;
    /**
     * Warnungen des Planungsalgorithmus. Leer wenn kein Problem erkannt wurde. Mögliche Einträge: - `\"deadline-missed:uuid\"` – Einmaliger Task konnte vor seiner Deadline   nicht vollständig eingeplant werden. Das verfügbare Tagesbudget   (nach Abzug von RecurringTemplates, Pausen und Pinned/Completed Entries)   reichte nicht aus, um den Task rechtzeitig zu platzieren. 
     */
    warnings: Array<string>;
    entries: Array<ScheduleEntry>;
}

