/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CognitiveLoad } from './cognitiveLoad';
import { TaskStatus } from './taskStatus';


export interface TaskResponse { 
    id: string;
    title: string;
    description?: string | null;
    status: TaskStatus;
    cognitiveLoad: CognitiveLoad;
    /**
     * Geschätzte Arbeitsdauer in Minuten
     */
    estimatedDurationMinutes: number;
    deadline?: string | null;
    /**
     * Frühestes Startdatum des Tasks (optional). Der Planungsalgorithmus plant diesen Task **nicht vor** diesem Datum ein. Nützlich für Tasks, die erst ab einem bestimmten Datum relevant sind (z.B. „nach dem Meeting am Montag starten\"). 
     */
    startDate?: string | null;
    /**
     * Gesetzt wenn dieser Task durch automatisches Task-Splitting entstanden ist (Ursprungs-Task-Referenz)
     */
    parentTaskId?: string | null;
    /**
     * Aktuell immer der eingeloggte Nutzer. Vorbereitet für zukünftige Team-Features.
     */
    ownerId: string;
    organizationId: string;
    completedAt?: string | null;
    createdAt: string;
    updatedAt: string;
}
export namespace TaskResponse {
}


