/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';
import { CognitiveLoad } from './cognitiveLoad';


export interface UpdateRecurringTemplateRequest { 
    title: string;
    description?: string | null;
    cognitiveLoad: CognitiveLoad;
    durationMinutes: number;
    recurrenceRule: RecurrenceRule;
    preferredStartTime?: string | null;
}
export namespace UpdateRecurringTemplateRequest {
}


