/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateOrganizationSettingsRequest { 
    name?: string;
    /**
     * Domain-Whitelist setzen oder mit null entfernen
     */
    allowedDomain?: string | null;
}

