/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurrenceRule } from './recurrenceRule';
import { CognitiveLoad } from './cognitiveLoad';


export interface UpdateTaskRequest { 
    title: string;
    description?: string | null;
    cognitiveLoad: CognitiveLoad;
    estimatedDurationMinutes: number;
    deadline?: string | null;
    recurrence?: RecurrenceRule;
}
export namespace UpdateTaskRequest {
}


