/**
 * Goaldone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkingHoursDayEntry } from './workingHoursDayEntry';


export interface UpsertWorkingHoursRequest { 
    /**
     * Alle 7 Wochentage (Mo–So) müssen angegeben werden, jeder genau einmal
     */
    days: Array<WorkingHoursDayEntry>;
}

